#ifndef PINS_H_
#define PINS_H_

#define LED_BOARD_PORT    GPIO_PORTC
#define OUT_LCD_DB4_PORT	GPIO_PORTA
#define OUT_LCD_DB5_PORT	GPIO_PORTA
#define OUT_LCD_DB6_PORT	GPIO_PORTA
#define OUT_LCD_DB7_PORT	GPIO_PORTA
#define OUT_LCD_EN_PORT		GPIO_PORTB
#define OUT_LCD_RW_PORT		GPIO_PORTA
#define OUT_LCD_RS_PORT		GPIO_PORTB
#define SPI_SCLK_PORT     GPIO_PORTA
#define SPI_MOSI_PORT     GPIO_PORTA
#define SPI_CS_PORT       GPIO_PORTA
#define SPI_MISO_PORT     GPIO_PORTA

#define LED_BOARD_PIN		  5
#define OUT_LCD_DB4_PIN		8
#define OUT_LCD_DB5_PIN		9
#define OUT_LCD_DB6_PIN		20
#define OUT_LCD_DB7_PIN		21
#define OUT_LCD_EN_PIN		30
#define OUT_LCD_RW_PIN		20
#define OUT_LCD_RS_PIN		31
#define SPI_SCLK_PIN      8
#define SPI_MOSI_PIN      9
#define SPI_CS_PIN        20
#define SPI_MISO_PIN      21

#endif /* PINS_H_ */
