#include "backlight.h"
#include "chip.h"
#include "pins.h"

#define BACKLIGHT_TIMER				LPC_TIMER32_1
#define BACKLIGHT_TIMER_M_RESET		0
#define BACKLIGHT_TIMER_M_OUT		3
#define BACKLIGHT_IOCON_FUNC		2
//#define BACKLIGHT_TIMER_FREQ		1000000U
#define BACKLIGHT_TIMER_PWM_FREQ	10000U
#define BACKLIGHT_PWM_MAX_VALUE		15U

void BACKLIGHT_Init(void)
{
	Chip_IOCON_PinMuxSet(LPC_IOCON, BACKLIGHT_PORT, BACKLIGHT_PIN, BACKLIGHT_IOCON_FUNC);

	Chip_TIMER_Init(BACKLIGHT_TIMER);
	Chip_TIMER_PrescaleSet(BACKLIGHT_TIMER, SystemCoreClock / BACKLIGHT_TIMER_PWM_FREQ / BACKLIGHT_PWM_MAX_VALUE  - 1);
	LPC_TIMER32_1->PWMC = (1UL << BACKLIGHT_TIMER_M_OUT);
	Chip_TIMER_SetMatch(BACKLIGHT_TIMER, BACKLIGHT_TIMER_M_RESET, BACKLIGHT_PWM_MAX_VALUE - 1);
	Chip_TIMER_ResetOnMatchEnable(BACKLIGHT_TIMER, BACKLIGHT_TIMER_M_RESET);
	Chip_TIMER_SetMatch(BACKLIGHT_TIMER, BACKLIGHT_TIMER_M_OUT, 5);
	Chip_TIMER_Enable(BACKLIGHT_TIMER);
}

void BACKLIGHT_SetValue(uint8_t value)
{
	if (value >= BACKLIGHT_PWM_MAX_VALUE) {
		value = BACKLIGHT_PWM_MAX_VALUE - 1;
	}
	Chip_TIMER_SetMatch(BACKLIGHT_TIMER, BACKLIGHT_TIMER_M_OUT, value);
}
